# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < https://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < https://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < https://docs.platformio.org/page/userguide/cmd_ci.html >
#
#
# Please choose one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#


#
# Template #1: General project. Test it using existing `platformio.ini`.
#

# language: python
# python:
#     - "2.7"

# sudo: false
# cache:
#     directories:
#         - "~/.platformio"

# install:
#     - pip install -U platformio
#     - platformio update

# script:
#     - platformio run



# Template #2: The project is intended to be used as a library with examples.

# $BUILDID="build-$(Get-RANDOM)"
# $INSTANCE="travisci/ci-garnet:packer-1515445631-7dfb2e1"
# docker run --name $BUILDID -dit $INSTANCE /sbin/init
# docker exec -it $BUILDID bash -l
# cd usr/src
# git clone https://github.com/jaredbebb/environmentControl.git
# cd environmentControl
# travis-build


language: python
python:
    - "3.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src/
    - PLATFORMIO_CI_SRC=extra/
    - PLATFORMIO_CI_SRC=test/unittest_env_config.cpp
    - PLATFORMIO_CI_SRC=test

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio run --environment nodemcuv2 --target 

deploy:
  on:
    repo: jaredbebb/Object-Detection-System
    all_branches: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  skip_cleanup: true
  provider: releases
  overwrite: true
  api_key:
    secure: $GH_REPO_TOKEN
  file: ".pio/build/nodemcuv2/firmware.bin"
